[workspace]
# Use the latest resolver available
resolver = "3"
# Include both parts of the library in the workspace
members = [
    "vetis",
    #"vetis-macros",
    #"examples/simple",
]

[profile.release]
strip = true
opt-level = "z" 
lto = true
codegen-units = 1
panic = "abort"
